CREATE TABLE orders (
    id BIGSERIAL PRIMARY KEY,
    order_number TEXT UNIQUE NOT NULL,
    user_id UUID REFERENCES auth.users(id),
    customer_type TEXT,
    subtotal NUMERIC NOT NULL,
    tax_amount NUMERIC NOT NULL,
    discount_amount NUMERIC DEFAULT 0,
    total_amount NUMERIC NOT NULL,
    coupon_code TEXT,
    loyalty_points_used INTEGER DEFAULT 0,
    payment_method TEXT,
    payment_status TEXT CHECK (payment_status IN ('pending',
    'paid',
    'failed',
    'refunded')) DEFAULT 'pending',
    order_status TEXT CHECK (order_status IN ('pending',
    'processing',
    'shipped',
    'delivered',
    'cancelled')) DEFAULT 'pending',
    shipping_address JSONB,
    billing_address JSONB,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);