CREATE TABLE products (
    id BIGSERIAL PRIMARY KEY,
    product_code TEXT UNIQUE,
    barcode TEXT,
    mpn TEXT,
    shelf_code TEXT,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    description TEXT,
    brand_id BIGINT,
    category_id BIGINT,
    base_price NUMERIC NOT NULL,
    tax_rate NUMERIC DEFAULT 20,
    origin TEXT,
    width NUMERIC,
    height NUMERIC,
    depth NUMERIC,
    desi NUMERIC,
    weight NUMERIC,
    stock INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    is_featured BOOLEAN DEFAULT false,
    view_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);